apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-hwc-subchart
  namespace: argo
spec:
  project: default
  source:
    repoURL: 'https://github.com/participant-fifteen/hwc-subchart'
    path: test
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hwc-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true